version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: taskManager
    volumes:
      - db_data:/var/lib/mysql
      - ./initDatabase.sql:/docker-entrypoint-initdb.d/initDatabase.sql:ro
    ports:
      - "3306:3306"

  backend:
    image: sergiomontero97/liferay_academy_backend:latest
    container_name: liferay_academy_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskManager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: sergiomontero97/liferay_academy_frontend:latest
    container_name: liferay_academy_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: